// src/views/admin/OrderManager.vue
// OrderManager.vue
<template>
  <div class="order-manager">
    <h2 class="text-2xl font-bold mb-4">Gestión de Pedidos</h2>
    
    <!-- Acciones masivas -->
    <div class="bg-white p-4 rounded-lg shadow mb-6">
      <div class="flex flex-wrap items-center justify-between gap-4">
        <div class="flex items-center">
          <input 
            type="checkbox" 
            :checked="allSelected"
            @change="toggleSelectAll"
            class="h-5 w-5 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
          />
          <label class="ml-2 text-sm text-gray-700">Seleccionar todos</label>
        </div>
        
        <div class="flex items-center">
          <span class="mr-2 text-sm text-gray-700">{{ selectedCount }} pedidos seleccionados</span>
          <button 
            @click="confirmDeleteSelected"
            :disabled="selectedCount === 0"
            :class="[
              'px-4 py-2 rounded-md text-sm font-medium',
              selectedCount > 0 
                ? 'bg-red-600 text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500'
                : 'bg-gray-300 text-gray-500 cursor-not-allowed'
            ]"
          >
            Eliminar seleccionados
          </button>
        </div>
      </div>
    </div>
    
    <!-- Lista de pedidos -->
    <div class="bg-white rounded-lg shadow">
      <div v-if="loading" class="text-center py-8">
        <p>Cargando pedidos...</p>
      </div>
      
      <div v-else-if="orders.length === 0" class="text-center py-8">
        <p>No hay pedidos registrados.</p>
      </div>
      
      <div v-else>
        <!-- Vista móvil: tarjetas -->
        <div class="md:hidden">
          <div v-for="order in orders" :key="order.id" class="border-b border-gray-200 p-4">
            <div class="flex items-center justify-between mb-2">
              <div class="flex items-center">
                <input 
                  type="checkbox" 
                  :checked="isSelected(order.id)"
                  @change="toggleSelect(order.id)"
                  class="h-5 w-5 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
                />
                <span class="ml-2 font-medium">Pedido #{{ order.id.substring(0, 8) }}</span>
              </div>
              <span 
                :class="[
                  'px-2 py-1 text-xs font-semibold rounded-full',
                  getStatusClass(order.status)
                ]"
              >
                {{ getStatusName(order.status) }}
              </span>
            </div>
            
            <div class="text-sm text-gray-600 mb-1">
              <span>{{ formatDate(order.created_at) }}</span>
            </div>
            
            <div class="text-sm font-medium mb-1">
              Total: ${{ order.total.toFixed(2) }}
            </div>
            
            <div class="text-sm text-gray-600 mb-3">
              {{ order.products.length }} productos
            </div>
            
            <div class="flex justify-end space-x-2">
              <button 
                @click="deleteOrder(order.id)" 
                class="px-3 py-1 bg-red-100 text-red-800 rounded-md text-sm hover:bg-red-200"
              >
                Eliminar
              </button>
            </div>
          </div>
        </div>
        
        <!-- Vista desktop: tabla -->
        <div class="hidden md:block overflow-x-auto">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-10">
                  <input 
                    type="checkbox" 
                    :checked="allSelected"
                    @change="toggleSelectAll"
                    class="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
                  />
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">ID</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Fecha</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Total</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Productos</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Estado</th>
                <th scope="col" class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Acciones</th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              <tr v-for="order in orders" :key="order.id">
                <td class="px-6 py-4 whitespace-nowrap">
                  <input 
                    type="checkbox" 
                    :checked="isSelected(order.id)"
                    @change="toggleSelect(order.id)"
                    class="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
                  />
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                  {{ order.id.substring(0, 8) }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                  {{ formatDate(order.created_at) }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                  ${{ order.total.toFixed(2) }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                  {{ order.products.length }} items
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <span 
                    :class="[
                      'px-2 inline-flex text-xs leading-5 font-semibold rounded-full',
                      getStatusClass(order.status)
                    ]"
                  >
                    {{ getStatusName(order.status) }}
                  </span>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <button 
                    @click="deleteOrder(order.id)" 
                    class="text-red-600 hover:text-red-900"
                  >
                    Eliminar
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    
    <!-- Modal de confirmación -->
    <div v-if="showConfirmModal" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div class="bg-white rounded-lg max-w-md w-full p-6">
        <h3 class="text-lg font-medium text-gray-900 mb-4">Confirmar eliminación</h3>
        <p class="text-sm text-gray-500 mb-6">
          ¿Estás seguro de que deseas eliminar {{ selectedCount }} pedidos? Esta acción no se puede deshacer.
        </p>
        <div class="flex justify-end space-x-3">
          <button 
            @click="showConfirmModal = false" 
            class="px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50"
          >
            Cancelar
          </button>
          <button 
            @click="deleteSelected" 
            class="px-4 py-2 bg-red-600 border border-transparent rounded-md shadow-sm text-sm font-medium text-white hover:bg-red-700"
          >
            Eliminar
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { useOrderStore } from '../../stores/orderStore';

// Estado
const orderStore = useOrderStore();
const loading = ref(false);
const showConfirmModal = ref(false);

// Computed
const orders = computed(() => orderStore.getOrders());
const selectedOrders = computed(() => orderStore.getSelectedOrders());
const selectedCount = computed(() => selectedOrders.value.length);
const allSelected = computed(() => {
  return orders.value.length > 0 && selectedCount.value === orders.value.length;
});

// Métodos
const fetchOrders = async () => {
  loading.value = true;
  await orderStore.fetchOrders();
  loading.value = false;
};

const isSelected = (id: string) => {
  return selectedOrders.value.includes(id);
};

const toggleSelect = (id: string) => {
  orderStore.selectOrder(id, !isSelected(id));
};

const toggleSelectAll = (event) => {
  orderStore.selectAllOrders(event.target.checked);
};

const confirmDeleteSelected = () => {
  if (selectedCount.value > 0) {
    showConfirmModal.value = true;
  }
};

const deleteSelected = async () => {
  loading.value = true;
  showConfirmModal.value = false;
  
  try {
    const result = await orderStore.deleteMultipleOrders(selectedOrders.value);
    
    if (result.success) {
      alert(`${selectedCount.value} pedidos eliminados correctamente`);
    } else {
      alert(`Error al eliminar pedidos: ${result.error}`);
    }
  } catch (error) {
    console.error('Error al eliminar pedidos:', error);
    alert('Ocurrió un error al eliminar los pedidos');
  } finally {
    loading.value = false;
  }
};

const deleteOrder = async (id: string) => {
  if (!confirm('¿Estás seguro de que deseas eliminar este pedido?')) {
    return;
  }
  
  loading.value = true;
  
  try {
    const result = await orderStore.deleteOrder(id);
    
    if (result.success) {
      alert('Pedido eliminado correctamente');
    } else {
      alert(`Error al eliminar el pedido: ${result.error}`);
    }
  } catch (error) {
    console.error('Error al eliminar el pedido:', error);
    alert('Ocurrió un error al eliminar el pedido');
  } finally {
    loading.value = false;
  }
};

const formatDate = (dateString: string): string => {
  if (!dateString) return '';
  const date = new Date(dateString);
  return date.toLocaleDateString() + ' ' + date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
};

const getStatusName = (status: string): string => {
  const statuses = {
    'preparation': 'En preparación',
    'shipped': 'Enviado',
    'delivered': 'Entregado',
    'cancelled': 'Cancelado'
  };
  
  return statuses[status] || status;
};

const getStatusClass = (status: string): string => {
  const classes = {
    'preparation': 'bg-yellow-100 text-yellow-800',
    'shipped': 'bg-blue-100 text-blue-800',
    'delivered': 'bg-green-100 text-green-800',
    'cancelled': 'bg-red-100 text-red-800'
  };
  
  return classes[status] || 'bg-gray-100 text-gray-800';
};

// Ciclo de vida
onMounted(async () => {
  await fetchOrders();
});
</script>

<style scoped>
/* Estilos específicos para móvil */
@media (max-width: 768px) {
  .order-manager {
    padding-bottom: 80px; /* Espacio para evitar que los botones flotantes tapen contenido */
  }
}
</style>

// src/components/OrderManager.tsx
import React, { useState, useEffect } from 'react';
import { supabase } from '../lib/supabase';
import { toast } from 'react-hot-toast';
import { Order } from '../types';
import { 
  Trash2, 
  Eye, 
  ChevronDown, 
  ChevronUp, 
  Clock, 
  TruckIcon, 
  CheckCircle, 
  XCircle, 
  CreditCard 
} from 'lucide-react';
import { format } from 'date-fns';

const ORDER_STATUS_MAP = {
  pending: { label: 'Pendiente', color: 'bg-yellow-100 text-yellow-800' },
  processing: { label: 'Procesando', color: 'bg-blue-100 text-blue-800' },
  shipped: { label: 'Enviado', color: 'bg-purple-100 text-purple-800' },
  delivered: { label: 'Entregado', color: 'bg-green-100 text-green-800' },
  cancelled: { label: 'Cancelado', color: 'bg-red-100 text-red-800' }
};

const PAYMENT_STATUS_MAP = {
  pending: { label: 'Pendiente', color: 'bg-yellow-100 text-yellow-800' },
  paid: { label: 'Pagado', color: 'bg-green-100 text-green-800' },
  failed: { label: 'Fallido', color: 'bg-red-100 text-red-800' }
};

const OrderManager: React.FC = () => {
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [expandedOrderId, setExpandedOrderId] = useState<string | null>(null);
  const [showOrderDetailModal, setShowOrderDetailModal] = useState(false);
  const [selectedOrder, setSelectedOrder] = useState<Order | null>(null);
  const [selectedOrders, setSelectedOrders] = useState<string[]>([]);
  const [selectAll, setSelectAll] = useState(false);
  const [showDeleteConfirmation, setShowDeleteConfirmation] = useState(false);

  useEffect(() => {
    loadOrders();
  }, []);

  const loadOrders = async () => {
    try {
      setLoading(true);
      setError(null);
      
      // Consulta básica para obtener solo los pedidos
      const { data: ordersData, error: ordersError } = await supabase
        .from('orders')
        .select('*')
        .order('created_at', { ascending: false });

      if (ordersError) {
        console.error('Error al cargar pedidos:', ordersError);
        setError('Error al cargar pedidos: ' + ordersError.message);
        toast.error('Error al cargar los pedidos');
        setLoading(false);
        return;
      }
      
      // Si no hay pedidos, establecer array vacío y terminar
      if (!ordersData || ordersData.length === 0) {
        console.log('No se encontraron pedidos');
        setOrders([]);
        setLoading(false);
        return;
      }
      
      // Establecer los pedidos con información básica
      const basicOrders = ordersData.map(order => ({
        ...order,
        order_items: []
      }));
      
      // Actualizar el estado con la información básica primero
      setOrders(basicOrders);
      
      // Limpiar selecciones
      setSelectedOrders([]);
      setSelectAll(false);
      
      setLoading(false);
    } catch (error: any) {
      console.error('Error general al cargar pedidos:', error);
      setError('Error general: ' + error.message);
      toast.error('Error al cargar los pedidos');
      setLoading(false);
    }
  };

  const handleDeleteOrder = async (orderId: string) => {
    if (!confirm('¿Estás seguro de que quieres eliminar este pedido? Esta acción no se puede deshacer.')) {
      return;
    }

    try {
      // Primero eliminamos los items del pedido
      const { error: itemsError } = await supabase
        .from('order_items')
        .delete()
        .eq('order_id', orderId);

      if (itemsError) throw itemsError;

      // Luego eliminamos el pedido
      const { error } = await supabase
        .from('orders')
        .delete()
        .eq('id', orderId);

      if (error) throw error;
      
      toast.success('Pedido eliminado exitosamente');
      loadOrders();
      
      // Si el pedido eliminado es el que estaba seleccionado, cerramos el modal
      if (selectedOrder?.id === orderId) {
        setShowOrderDetailModal(false);
        setSelectedOrder(null);
      }
    } catch (error: any) {
      console.error('Error deleting order:', error);
      toast.error('Error al eliminar el pedido');
    }
  };

  const handleDeleteSelectedOrders = async () => {
    setShowDeleteConfirmation(false);
    
    if (selectedOrders.length === 0) {
      toast.error('No hay pedidos seleccionados para eliminar');
      return;
    }

    try {
      setLoading(true);
      
      // Primero eliminamos los items de los pedidos seleccionados
      const { error: itemsError } = await supabase
        .from('order_items')
        .delete()
        .in('order_id', selectedOrders);

      if (itemsError) throw itemsError;

      // Luego eliminamos los pedidos
      const { error } = await supabase
        .from('orders')
        .delete()
        .in('id', selectedOrders);

      if (error) throw error;
      
      toast.success(`${selectedOrders.length} pedidos eliminados exitosamente`);
      
      // Recargar pedidos y limpiar selecciones
      await loadOrders();
      
    } catch (error: any) {
      console.error('Error deleting orders:', error);
      toast.error('Error al eliminar los pedidos');
    } finally {
      setLoading(false);
    }
  };

  const handleUpdateOrderStatus = async (orderId: string, status: Order['status']) => {
    try {
      const { error } = await supabase
        .from('orders')
        .update({ status })
        .eq('id', orderId);

      if (error) throw error;
      toast.success('Estado del pedido actualizado');
      loadOrders();
    } catch (error: any) {
      console.error('Error updating order status:', error);
      toast.error('Error al actualizar el estado del pedido');
    }
  };
  
  const handleViewOrderDetails = async (order: Order) => {
    console.log('Visualizando detalles del pedido:', order.id);
    
    try {
      // Cargar datos completos del pedido para asegurar que tenemos toda la información
      const { data: orderData, error: orderError } = await supabase
        .from('orders')
        .select('*')
        .eq('id', order.id)
        .single();
        
      if (orderError) {
        console.error('Error al cargar detalles del pedido:', orderError);
        toast.error('Error al cargar detalles del pedido');
        return;
      }
      
      // Cargar items del pedido si existen
      const { data: orderItems, error: itemsError } = await supabase
        .from('order_items')
        .select('*, products(*)')
        .eq('order_id', order.id);
        
      if (itemsError) {
        console.error('Error al cargar items del pedido:', itemsError);
      }
      
      // Combinar datos y establecer el pedido seleccionado
      const completeOrder = {
        ...orderData,
        items: orderItems || [],
      };
      
      console.log('Pedido completo cargado:', completeOrder);
      setSelectedOrder(completeOrder);
      setShowOrderDetailModal(true);
    } catch (error) {
      console.error('Error general al cargar detalles del pedido:', error);
      toast.error('Error al cargar detalles del pedido');
    }
  };

  const toggleOrderExpand = (orderId: string) => {
    if (expandedOrderId === orderId) {
      setExpandedOrderId(null);
    } else {
      setExpandedOrderId(orderId);
    }
  };

  const handleSelectOrder = (orderId: string, isChecked: boolean) => {
    if (isChecked) {
      setSelectedOrders(prev => [...prev, orderId]);
    } else {
      setSelectedOrders(prev => prev.filter(id => id !== orderId));
      setSelectAll(false);
    }
  };

  const handleSelectAll = (isChecked: boolean) => {
    setSelectAll(isChecked);
    if (isChecked) {
      setSelectedOrders(orders.map(order => order.id));
    } else {
      setSelectedOrders([]);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="animate-spin rounded-full h-32 w-32 border-b-2 border-indigo-600"></div>
      </div>
    );
  }

  return (
    <div>
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-xl font-semibold text-gray-900">
          Pedidos
        </h2>
        
        {selectedOrders.length > 0 && (
          <button
            onClick={() => setShowDeleteConfirmation(true)}
            className="inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500"
          >
            <Trash2 className="h-5 w-5 mr-2" />
            Eliminar seleccionados ({selectedOrders.length})
          </button>
        )}
      </div>

      {error && (
        <div className="bg-red-50 border-l-4 border-red-400 p-4 mb-6">
          <div className="flex">
            <div className="flex-shrink-0">
              <XCircle className="h-5 w-5 text-red-400" />
            </div>
            <div className="ml-3">
              <p className="text-sm text-red-700">{error}</p>
            </div>
          </div>
        </div>
      )}

      {orders.length === 0 ? (
        <div className="text-center py-12">
          <p className="text-gray-500">No hay pedidos disponibles.</p>
        </div>
      ) : (
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th scope="col" className="px-2 py-3 text-left">
                  <input
                    type="checkbox"
                    checked={selectAll}
                    onChange={(e) => handleSelectAll(e.target.checked)}
                    className="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
                  />
                </th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Pedido
                </th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Cliente
                </th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Estado
                </th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Pago
                </th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Fecha
                </th>
                <th scope="col" className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Acciones
                </th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {orders.map((order) => (
                <React.Fragment key={order.id}>
                  <tr className={expandedOrderId === order.id ? 'bg-gray-50' : ''}>
                    <td className="px-2 py-4 whitespace-nowrap">
                      <input
                        type="checkbox"
                        checked={selectedOrders.includes(order.id)}
                        onChange={(e) => handleSelectOrder(order.id, e.target.checked)}
                        className="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
                      />
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm font-medium text-gray-900">
                        #{order.id.substring(0, 8)}
                      </div>
                      <div className="text-sm text-gray-500">
                        {order.total_amount ? `$${order.total_amount.toFixed(2)}` : 'N/A'}
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm text-gray-900">
                        {order.customer_name || 'N/A'}
                      </div>
                      <div className="text-sm text-gray-500">
                        {order.customer_email || 'N/A'}
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${ORDER_STATUS_MAP[order.status]?.color || 'bg-gray-100 text-gray-800'}`}>
                        {ORDER_STATUS_MAP[order.status]?.label || order.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${PAYMENT_STATUS_MAP[order.payment_status]?.color || 'bg-gray-100 text-gray-800'}`}>
                        {PAYMENT_STATUS_MAP[order.payment_status]?.label || order.payment_status}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {order.created_at ? format(new Date(order.created_at), 'dd/MM/yyyy HH:mm') : 'N/A'}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                      <button
                        onClick={() => handleViewOrderDetails(order)}
                        className="text-indigo-600 hover:text-indigo-900 mr-3"
                      >
                        <Eye className="h-5 w-5" />
                      </button>
                      <button
                        onClick={() => toggleOrderExpand(order.id)}
                        className="text-gray-600 hover:text-gray-900 mr-3"
                      >
                        {expandedOrderId === order.id ? (
                          <ChevronUp className="h-5 w-5" />
                        ) : (
                          <ChevronDown className="h-5 w-5" />
                        )}
                      </button>
                      <button
                        onClick={() => handleDeleteOrder(order.id)}
                        className="text-red-600 hover:text-red-900"
                      >
                        <Trash2 className="h-5 w-5" />
                      </button>
                    </td>
                  </tr>
                  {expandedOrderId === order.id && (
                    <tr>
                      <td colSpan={7} className="px-6 py-4 bg-gray-50">
                        <div className="text-sm text-gray-900 mb-2">
                          <strong>Dirección de envío:</strong> {order.shipping_address || 'No disponible'}
                        </div>
                        <div className="text-sm text-gray-900 mb-2">
                          <strong>Método de pago:</strong> {order.payment_method || 'No disponible'}
                        </div>
                        <div className="text-sm text-gray-900 mb-4">
                          <strong>Notas:</strong> {order.notes || 'Sin notas'}
                        </div>
                        <div className="flex space-x-2">
                          <button
                            onClick={() => handleUpdateOrderStatus(order.id, 'pending')}
                            className="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-yellow-700 bg-yellow-100 hover:bg-yellow-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-yellow-500"
                          >
                            <Clock className="h-4 w-4 mr-1" />
                            Pendiente
                          </button>
                          <button
                            onClick={() => handleUpdateOrderStatus(order.id, 'processing')}
                            className="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-blue-700 bg-blue-100 hover:bg-blue-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                          >
                            <CreditCard className="h-4 w-4 mr-1" />
                            Procesando
                          </button>
                          <button
                            onClick={() => handleUpdateOrderStatus(order.id, 'shipped')}
                            className="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-purple-700 bg-purple-100 hover:bg-purple-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500"
                          >
                            <TruckIcon className="h-4 w-4 mr-1" />
                            Enviado
                          </button>
                          <button
                            onClick={() => handleUpdateOrderStatus(order.id, 'delivered')}
                            className="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-green-700 bg-green-100 hover:bg-green-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500"
                          >
                            <CheckCircle className="h-4 w-4 mr-1" />
                            Entregado
                          </button>
                          <button
                            onClick={() => handleUpdateOrderStatus(order.id, 'cancelled')}
                            className="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-red-700 bg-red-100 hover:bg-red-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500"
                          >
                            <XCircle className="h-4 w-4 mr-1" />
                            Cancelado
                          </button>
                        </div>
                      </td>
                    </tr>
                  )}
                </React.Fragment>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Modal de confirmación para eliminar múltiples pedidos */}
      {showDeleteConfirmation && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg max-w-md w-full p-6">
            <h3 className="text-lg font-medium text-gray-900 mb-4">
              Confirmar eliminación
            </h3>
            <p className="text-sm text-gray-500 mb-4">
              ¿Estás seguro de que quieres eliminar {selectedOrders.length} pedidos? Esta acción no se puede deshacer.
            </p>
            <div className="flex justify-end space-x-3">
              <button
                onClick={() => setShowDeleteConfirmation(false)}
                className="bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
              >
                Cancelar
              </button>
              <button
                onClick={handleDeleteSelectedOrders}
                className="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500"
              >
                <Trash2 className="h-5 w-5 mr-2" />
                Eliminar
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Modal de detalles del pedido */}
      {showOrderDetailModal && selectedOrder && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg max-w-4xl w-full p-6 max-h-[90vh] overflow-y-auto">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-medium text-gray-900">
                Detalles del Pedido #{selectedOrder.id.substring(0, 8)}
              </h3>
              <button
                onClick={() => setShowOrderDetailModal(false)}
                className="text-gray-400 hover:text-gray-500"
              >
                <XCircle className="h-6 w-6" />
              </button>
            </div>

            <div className="border-t border-gray-200 py-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <h4 className="text-sm font-medium text-gray-500 mb-2">Información del Cliente</h4>
                  <p className="text-sm text-gray-900">Nombre: {selectedOrder.customer_name || 'N/A'}</p>
                  <p className="text-sm text-gray-900">Email: {selectedOrder.customer_email || 'N/A'}</p>
                  <p className="text-sm text-gray-900">Teléfono: {selectedOrder.customer_phone || 'N/A'}</p>
                </div>
                <div>
                  <h4 className="text-sm font-medium text-gray-500 mb-2">Información del Pedido</h4>
                  <p className="text-sm text-gray-900">Fecha: {selectedOrder.created_at ? format(new Date(selectedOrder.created_at), 'dd/MM/yyyy HH:mm') : 'N/A'}</p>
                  <p className="text-sm text-gray-900">Estado: <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${ORDER_STATUS_MAP[selectedOrder.status]?.color || 'bg-gray-100 text-gray-800'}`}>
                    {ORDER_STATUS_MAP[selectedOrder.status]?.label || selectedOrder.status}
                  </span></p>
                  <p className="text-sm text-gray-900">Pago: <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${PAYMENT_STATUS_MAP[selectedOrder.payment_status]?.color || 'bg-gray-100 text-gray-800'}`}>
                    {PAYMENT_STATUS_MAP[selectedOrder.payment_status]?.label || selectedOrder.payment_status}
                  </span></p>
                </div>
              </div>
            </div>

            <div className="border-t border-gray-200 py-4">
              <h4 className="text-sm font-medium text-gray-500 mb-2">Dirección de Envío</h4>
              <p className="text-sm text-gray-900">{selectedOrder.shipping_address || 'No disponible'}</p>
            </div>

            <div className="border-t border-gray-200 py-4">
              <h4 className="text-sm font-medium text-gray-500 mb-2">Productos</h4>
              {selectedOrder.items && selectedOrder.items.length > 0 ? (
                <div className="overflow-x-auto">
                  <table className="min-w-full divide-y divide-gray-200">
                    <thead className="bg-gray-50">
                      <tr>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Producto
                        </th>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Cantidad
                        </th>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Precio
                        </th>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Subtotal
                        </th>
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                      {selectedOrder.items.map((item, index) => (
                        <tr key={index}>
                          <td className="px-6 py-4 whitespace-nowrap">
                            <div className="flex items-center">
                              {item.products?.images && item.products.images[0] && (
                                <div className="flex-shrink-0 h-10 w-10 mr-4">
                                  <img
                                    className="h-10 w-10 rounded-full object-cover"
                                    src={item.products.images[0]}
                                    alt={item.products?.name || 'Producto'}
                                  />
                                </div>
                              )}
                              <div>
                                <div className="text-sm font-medium text-gray-900">
                                  {item.products?.name || 'Producto desconocido'}
                                </div>
                                {item.color && (
                                  <div className="text-xs text-gray-500">
                                    Color: {item.color}
                                  </div>
                                )}
                              </div>
                            </div>
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                            {item.quantity || 1}
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                            ${item.price?.toFixed(2) || 'N/A'}
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                            ${((item.price || 0) * (item.quantity || 1)).toFixed(2)}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                    <tfoot>
                      <tr>
                        <td colSpan={3} className="px-6 py-4 text-right text-sm font-medium text-gray-900">
                          Total:
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                          ${selectedOrder.total_amount?.toFixed(2) || 'N/A'}
                        </td>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              ) : (
                <p className="text-sm text-gray-500">No hay productos disponibles para este pedido.</p>
              )}
            </div>

            <div className="border-t border-gray-200 py-4">
              <h4 className="text-sm font-medium text-gray-500 mb-2">Notas</h4>
              <p className="text-sm text-gray-900">{selectedOrder.notes || 'Sin notas'}</p>
            </div>

            <div className="flex justify-end mt-4">
              <button
                onClick={() => setShowOrderDetailModal(false)}
                className="bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
              >
                Cerrar
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default OrderManager;
