// src/components/PromotionManager.tsx
import React, { useState, useEffect } from 'react';
import { supabase } from '../lib/supabase';
import { toast } from 'react-hot-toast';
import { Promotion, Product } from '../types';
import { usePromotionStore } from '../stores/promotionStore';

interface PromotionManagerProps {
  onPromotionCreated?: () => void;
}

const PromotionManager: React.FC<PromotionManagerProps> = ({ onPromotionCreated }) => {
  const promotionStore = usePromotionStore();
  const [products, setProducts] = useState<Product[]>([]);
  const [editingPromotion, setEditingPromotion] = useState<Promotion | null>(null);
  const [promotionForm, setPromotionForm] = useState({
    name: '',
    description: '',
    type: 'percentage' as Promotion['type'],
    value: 0,
    start_date: '',
    end_date: '',
    active: true,
    product_ids: [] as string[]
  });

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    try {
      await Promise.all([
        promotionStore.fetchPromotions(),
        fetchProducts()
      ]);
    } catch (error) {
      console.error('Error loading data:', error);
      toast.error('Error al cargar los datos');
    }
  };

  const fetchProducts = async () => {
    try {
      const { data, error } = await supabase
        .from('products')
        .select('*')
        .order('name');
      
      if (error) throw error;
      setProducts(data || []);
    } catch (error) {
      console.error('Error fetching products:', error);
      toast.error('Error al cargar los productos');
    }
  };

  const handleEditPromotion = (promotion: Promotion) => {
    setEditingPromotion(promotion);
    setPromotionForm({
      name: promotion.name,
      description: promotion.description || '',
      type: promotion.type,
      value: promotion.value || 0,
      start_date: promotion.start_date ? new Date(promotion.start_date).toISOString().split('T')[0] : '',
      end_date: promotion.end_date ? new Date(promotion.end_date).toISOString().split('T')[0] : '',
      active: promotion.active,
      product_ids: promotion.product_ids || []
    });
  };

  const handleNewPromotion = () => {
    setEditingPromotion(null);
    setPromotionForm({
      name: '',
      description: '',
      type: 'percentage',
      value: 0,
      start_date: '',
      end_date: '',
      active: true,
      product_ids: []
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    try {
      if (!promotionForm.name.trim()) {
        toast.error('El nombre de la promoción es obligatorio');
        return;
      }

      if (promotionForm.type === 'percentage' && (promotionForm.value <= 0 || promotionForm.value > 100)) {
        toast.error('El porcentaje debe estar entre 1 y 100');
        return;
      }

      if (promotionForm.type === 'fixed' && promotionForm.value <= 0) {
        toast.error('El valor del descuento debe ser mayor que 0');
        return;
      }

      if (promotionForm.product_ids.length === 0) {
        toast.error('Debes seleccionar al menos un producto');
        return;
      }

      const promotionData: Promotion = {
        name: promotionForm.name.trim(),
        description: promotionForm.description.trim(),
        type: promotionForm.type,
        value: promotionForm.value,
        active: promotionForm.active,
        start_date: promotionForm.start_date || undefined,
        end_date: promotionForm.end_date || undefined,
        product_ids: promotionForm.product_ids
      };

      let result;
      if (editingPromotion) {
        result = await promotionStore.updatePromotion(editingPromotion.id!, promotionData);
      } else {
        result = await promotionStore.createPromotion(promotionData);
      }

      if (result.success) {
        toast.success(editingPromotion ? 'Promoción actualizada' : 'Promoción creada');
        handleNewPromotion();
        if (onPromotionCreated) {
          onPromotionCreated();
        }
      } else {
        toast.error(result.error || 'Error al guardar la promoción');
      }
    } catch (error: any) {
      console.error('Error saving promotion:', error);
      toast.error('Error al guardar la promoción');
    }
  };

  const handleDeletePromotion = async (id: string) => {
    if (!window.confirm('¿Estás seguro de eliminar esta promoción?')) {
      return;
    }

    try {
      const result = await promotionStore.deletePromotion(id);
      if (result.success) {
        toast.success('Promoción eliminada');
      } else {
        toast.error(result.error || 'Error al eliminar la promoción');
      }
    } catch (error) {
      console.error('Error deleting promotion:', error);
      toast.error('Error al eliminar la promoción');
    }
  };

  return (
    <div className="bg-white p-6 rounded-lg shadow-lg">
      <h2 className="text-2xl font-bold mb-6">Gestión de Promociones</h2>
      
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Form */}
        <div>
          <h3 className="text-lg font-semibold mb-4">
            {editingPromotion ? 'Editar Promoción' : 'Nueva Promoción'}
          </h3>
          
          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="block text-sm font-medium mb-1">Nombre</label>
              <input
                type="text"
                value={promotionForm.name}
                onChange={(e) => setPromotionForm(prev => ({ ...prev, name: e.target.value }))}
                className="w-full p-2 border rounded"
                required
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-1">Descripción</label>
              <textarea
                value={promotionForm.description}
                onChange={(e) => setPromotionForm(prev => ({ ...prev, description: e.target.value }))}
                className="w-full p-2 border rounded"
                rows={3}
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-1">Tipo de Promoción</label>
              <select
                value={promotionForm.type}
                onChange={(e) => setPromotionForm(prev => ({ ...prev, type: e.target.value as Promotion['type'] }))}
                className="w-full p-2 border rounded"
              >
                <option value="percentage">Porcentaje de descuento</option>
                <option value="fixed">Descuento fijo</option>
                <option value="2x1">2x1</option>
                <option value="3x2">3x2</option>
                <option value="3x1">3x1</option>
              </select>
            </div>

            {(promotionForm.type === 'percentage' || promotionForm.type === 'fixed') && (
              <div>
                <label className="block text-sm font-medium mb-1">
                  {promotionForm.type === 'percentage' ? 'Porcentaje de descuento' : 'Valor del descuento'}
                </label>
                <input
                  type="number"
                  value={promotionForm.value}
                  onChange={(e) => setPromotionForm(prev => ({ ...prev, value: parseFloat(e.target.value) || 0 }))}
                  min="0"
                  max={promotionForm.type === 'percentage' ? "100" : undefined}
                  step="0.01"
                  className="w-full p-2 border rounded"
                  required
                />
              </div>
            )}

            <div>
              <label className="block text-sm font-medium mb-1">Fecha de inicio</label>
              <input
                type="date"
                value={promotionForm.start_date}
                onChange={(e) => setPromotionForm(prev => ({ ...prev, start_date: e.target.value }))}
                className="w-full p-2 border rounded"
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-1">Fecha de fin</label>
              <input
                type="date"
                value={promotionForm.end_date}
                onChange={(e) => setPromotionForm(prev => ({ ...prev, end_date: e.target.value }))}
                className="w-full p-2 border rounded"
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-1">Productos</label>
              <select
                multiple
                value={promotionForm.product_ids}
                onChange={(e) => {
                  const values = Array.from(e.target.selectedOptions, option => option.value);
                  setPromotionForm(prev => ({ ...prev, product_ids: values }));
                }}
                className="w-full p-2 border rounded"
                size={5}
              >
                {products.map(product => (
                  <option key={product.id} value={product.id}>
                    {product.name} - ${product.price}
                  </option>
                ))}
              </select>
              <p className="text-sm text-gray-500 mt-1">
                Mantén presionada la tecla Ctrl para seleccionar múltiples productos
              </p>
            </div>

            <div className="flex items-center">
              <input
                type="checkbox"
                checked={promotionForm.active}
                onChange={(e) => setPromotionForm(prev => ({ ...prev, active: e.target.checked }))}
                className="mr-2"
              />
              <label className="text-sm font-medium">Promoción activa</label>
            </div>

            <div className="flex space-x-4">
              <button
                type="submit"
                className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
              >
                {editingPromotion ? 'Actualizar' : 'Crear'} Promoción
              </button>
              
              {editingPromotion && (
                <button
                  type="button"
                  onClick={handleNewPromotion}
                  className="px-4 py-2 bg-gray-200 text-gray-700 rounded hover:bg-gray-300"
                >
                  Cancelar
                </button>
              )}
            </div>
          </form>
        </div>

        {/* List */}
        <div>
          <h3 className="text-lg font-semibold mb-4">Promociones Existentes</h3>
          
          <div className="space-y-4">
            {promotionStore.promotions.map(promotion => (
              <div
                key={promotion.id}
                className="border rounded p-4 space-y-2"
              >
                <div className="flex justify-between items-start">
                  <div>
                    <h4 className="font-semibold">{promotion.name}</h4>
                    {promotion.description && (
                      <p className="text-sm text-gray-600">{promotion.description}</p>
                    )}
                  </div>
                  <div className="flex space-x-2">
                    <button
                      onClick={() => handleEditPromotion(promotion)}
                      className="text-blue-600 hover:text-blue-800"
                    >
                      Editar
                    </button>
                    <button
                      onClick={() => handleDeletePromotion(promotion.id!)}
                      className="text-red-600 hover:text-red-800"
                    >
                      Eliminar
                    </button>
                  </div>
                </div>

                <div className="text-sm">
                  <p>
                    Tipo: {promotion.type === 'percentage' ? `${promotion.value}% de descuento` :
                          promotion.type === 'fixed' ? `$${promotion.value} de descuento` :
                          promotion.type === '2x1' ? 'Lleva 2, paga 1' :
                          promotion.type === '3x2' ? 'Lleva 3, paga 2' :
                          'Lleva 3, paga 1'}
                  </p>
                  <p>
                    Estado: <span className={promotion.active ? 'text-green-600' : 'text-red-600'}>
                      {promotion.active ? 'Activa' : 'Inactiva'}
                    </span>
                  </p>
                  {promotion.start_date && (
                    <p>Inicio: {new Date(promotion.start_date).toLocaleDateString()}</p>
                  )}
                  {promotion.end_date && (
                    <p>Fin: {new Date(promotion.end_date).toLocaleDateString()}</p>
                  )}
                  <p>
                    Productos: {promotion.product_ids?.length || 0} seleccionados
                  </p>
                </div>
              </div>
            ))}

            {promotionStore.promotions.length === 0 && (
              <p className="text-gray-500 text-center py-4">
                No hay promociones creadas
              </p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default PromotionManager;

// src/views/admin/PromotionManager.vue
// PromotionManager.vue
<template>
  <div class="promotion-manager">
    <h2 class="text-2xl font-bold mb-4">Gestión de Promociones</h2>
    
    <!-- Formulario de creación/edición -->
    <div class="bg-white p-4 rounded-lg shadow mb-6">
      <h3 class="text-lg font-semibold mb-3">{{ isEditing ? 'Editar Promoción' : 'Crear Nueva Promoción' }}</h3>
      
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Nombre</label>
          <input 
            v-model="form.name" 
            type="text" 
            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
            placeholder="Nombre de la promoción"
          />
        </div>
        
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Tipo</label>
          <select 
            v-model="form.type" 
            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="percentage">Porcentaje de descuento</option>
            <option value="fixed">Descuento fijo</option>
            <option value="discount">Descuento general</option>
            <option value="2x1">2x1</option>
            <option value="3x2">3x2</option>
            <option value="3x1">3x1</option>
          </select>
        </div>
        
        <div v-if="['percentage', 'fixed', 'discount'].includes(form.type)">
          <label class="block text-sm font-medium text-gray-700 mb-1">Valor</label>
          <input 
            v-model.number="form.value" 
            type="number" 
            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
            placeholder="Valor del descuento"
            min="0"
          />
        </div>
        
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Descripción</label>
          <textarea 
            v-model="form.description" 
            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
            placeholder="Descripción de la promoción"
            rows="2"
          ></textarea>
        </div>
        
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Fecha de inicio</label>
          <input 
            v-model="form.start_date" 
            type="date" 
            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>
        
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Fecha de fin</label>
          <input 
            v-model="form.end_date" 
            type="date" 
            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>
        
        <div class="flex items-center">
          <input 
            v-model="form.active" 
            type="checkbox" 
            class="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
          />
          <label class="ml-2 block text-sm text-gray-900">Activa</label>
        </div>
      </div>
      
      <div class="mt-4 flex justify-end space-x-3">
        <button 
          v-if="isEditing"
          @click="cancelEdit" 
          class="px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          Cancelar
        </button>
        <button 
          @click="savePromotion" 
          class="px-4 py-2 bg-blue-600 border border-transparent rounded-md shadow-sm text-sm font-medium text-white hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500"
          :disabled="loading"
        >
          {{ isEditing ? 'Actualizar' : 'Crear' }} Promoción
        </button>
      </div>
    </div>
    
    <!-- Lista de promociones -->
    <div class="bg-white p-4 rounded-lg shadow">
      <h3 class="text-lg font-semibold mb-3">Promociones Existentes</h3>
      
      <div v-if="loading" class="text-center py-4">
        <p>Cargando promociones...</p>
      </div>
      
      <div v-else-if="promotions.length === 0" class="text-center py-4">
        <p>No hay promociones creadas.</p>
      </div>
      
      <div v-else class="overflow-x-auto">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Nombre</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Tipo</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Valor</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Estado</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Fechas</th>
              <th scope="col" class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Acciones</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <tr v-for="promotion in promotions" :key="promotion.id">
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm font-medium text-gray-900">{{ promotion.name }}</div>
                <div class="text-sm text-gray-500">{{ promotion.description }}</div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <span class="text-sm text-gray-900">{{ getPromotionTypeName(promotion.type) }}</span>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <span v-if="['percentage', 'discount'].includes(promotion.type)" class="text-sm text-gray-900">
                  {{ promotion.value }}%
                </span>
                <span v-else-if="promotion.type === 'fixed'" class="text-sm text-gray-900">
                  ${{ promotion.value }}
                </span>
                <span v-else class="text-sm text-gray-900">-</span>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <span 
                  :class="[
                    'px-2 inline-flex text-xs leading-5 font-semibold rounded-full',
                    promotion.active ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
                  ]"
                >
                  {{ promotion.active ? 'Activa' : 'Inactiva' }}
                </span>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                <div v-if="promotion.start_date">Desde: {{ formatDate(promotion.start_date) }}</div>
                <div v-if="promotion.end_date">Hasta: {{ formatDate(promotion.end_date) }}</div>
                <div v-if="!promotion.start_date && !promotion.end_date">Sin límite de fechas</div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                <button 
                  @click="editPromotion(promotion)" 
                  class="text-blue-600 hover:text-blue-900 mr-3"
                >
                  Editar
                </button>
                <button 
                  @click="togglePromotionStatus(promotion.id)" 
                  class="text-yellow-600 hover:text-yellow-900 mr-3"
                >
                  {{ promotion.active ? 'Desactivar' : 'Activar' }}
                </button>
                <button 
                  @click="deletePromotion(promotion.id)" 
                  class="text-red-600 hover:text-red-900"
                >
                  Eliminar
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue';
import { usePromotionStore, type Promotion } from '../../stores/promotionStore';

// Estado
const promotionStore = usePromotionStore();
const loading = ref(false);
const isEditing = ref(false);
const editingId = ref<string | null>(null);

// Formulario
const form = ref<Promotion>({
  name: '',
  description: '',
  type: 'percentage',
  value: 0,
  active: true,
  start_date: '',
  end_date: '',
  product_ids: [],
  category_ids: []
});

// Computed
const promotions = computed(() => promotionStore.getPromotions());

// Métodos
const resetForm = () => {
  form.value = {
    name: '',
    description: '',
    type: 'percentage',
    value: 0,
    active: true,
    start_date: '',
    end_date: '',
    product_ids: [],
    category_ids: []
  };
  isEditing.value = false;
  editingId.value = null;
};

const savePromotion = async () => {
  loading.value = true;
  
  try {
    if (isEditing.value && editingId.value) {
      // Actualizar promoción existente
      const result = await promotionStore.updatePromotion(editingId.value, form.value);
      
      if (result.success) {
        alert('Promoción actualizada correctamente');
        resetForm();
      } else {
        alert(`Error al actualizar la promoción: ${result.error}`);
      }
    } else {
      // Crear nueva promoción
      const result = await promotionStore.createPromotion(form.value);
      
      if (result.success) {
        alert('Promoción creada correctamente');
        resetForm();
      } else {
        alert(`Error al crear la promoción: ${result.error}`);
      }
    }
  } catch (error) {
    console.error('Error al guardar la promoción:', error);
    alert('Ocurrió un error al guardar la promoción');
  } finally {
    loading.value = false;
  }
};

const editPromotion = (promotion: Promotion) => {
  form.value = { ...promotion };
  isEditing.value = true;
  editingId.value = promotion.id;
};

const cancelEdit = () => {
  resetForm();
};

const deletePromotion = async (id: string) => {
  if (!confirm('¿Estás seguro de que deseas eliminar esta promoción?')) {
    return;
  }
  
  loading.value = true;
  
  try {
    const result = await promotionStore.deletePromotion(id);
    
    if (result.success) {
      alert('Promoción eliminada correctamente');
    } else {
      alert(`Error al eliminar la promoción: ${result.error}`);
    }
  } catch (error) {
    console.error('Error al eliminar la promoción:', error);
    alert('Ocurrió un error al eliminar la promoción');
  } finally {
    loading.value = false;
  }
};

const togglePromotionStatus = async (id: string) => {
  loading.value = true;
  
  try {
    const result = await promotionStore.togglePromotionStatus(id);
    
    if (result.success) {
      alert('Estado de la promoción actualizado correctamente');
    } else {
      alert(`Error al actualizar el estado de la promoción: ${result.error}`);
    }
  } catch (error) {
    console.error('Error al actualizar el estado de la promoción:', error);
    alert('Ocurrió un error al actualizar el estado de la promoción');
  } finally {
    loading.value = false;
  }
};

const getPromotionTypeName = (type: string): string => {
  const types = {
    percentage: 'Porcentaje',
    fixed: 'Monto fijo',
    discount: 'Descuento',
    '2x1': '2x1',
    '3x2': '3x2',
    '3x1': '3x1'
  };
  
  return types[type] || type;
};

const formatDate = (dateString: string): string => {
  const date = new Date(dateString);
  return date.toLocaleDateString();
};

// Ciclo de vida
onMounted(async () => {
  loading.value = true;
  await promotionStore.fetchPromotions();
  loading.value = false;
});
</script>
